apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: mandelbrok8s
  labels:
    app: worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: docker.io/marcb76/mandelbrok8s-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: probes
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_URI
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
